# configs/fusion.yaml
# DeepFusionPose Model Specific Settings

model:
  seq_len: 60
  batch_size: 32
  epochs: 80
  lr: 0.0001
  weight_decay: 0.00001
  patience: 15
  dropout: 0.2
  n_mc: 50  # MC Dropout samples at inference
